version: '3.8'
services:
  app:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - postgres
      - redis
      - hardhat
    environment:
      DATABASE_URL: postgresql://user:password@postgres:5432/carbonx_dev
      REDIS_URL: redis://redis:6379
      WALLET_PRIVATE_KEY: 0xac0974bec39a17e36ba4a6b4d238ff944bacb478cbed5efcae784d7bf4f2ff80 # Hardhat default private key
      HARDHAT_NODE_URL: http://hardhat:8545

  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: carbonx_dev
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:6
    ports:
      - "6379:6379"

  hardhat:
    image: "node:18"
    working_dir: /usr/src/app
    command: "npx hardhat node"
    ports:
      - "8545:8545"
    volumes:
      - .:/usr/src/app

volumes:
  postgres_data:
